S2 us05 game detail part two
WildCodeSchool-2023-09/php-paris-p3-neoretro pull request #11
Opened 2024-01-11 10:41 UTC by Baptiste1828

2024-01-11 15:49 UTC, eddyjoncoux approved these changes

2024-01-12 12:09 UTC, mickaellambert requested changes

2024-01-12 12:09 UTC, mickaellambert commented on assets/scripts/carousel.js
T'as recodé toi même un carousel ?

2024-01-12 12:09 UTC, mickaellambert commented on src/Controller/GameController.php
> +<?php
Je suis pas censé avoir toutes les routes de game ici, juste celle qui permet d'afficher la page d'un jeu vu que l'US concernée est game detail

2024-01-12 12:09 UTC, mickaellambert commented on src/Form/GameType.php
Je suis pas censé avoir ce fichier si l'US ne concerne que l'affichage d'un jeu

2024-01-12 12:09 UTC, mickaellambert commented on templates/game/_delete_form.html.twig
Je suis pas censé avoir ce fichier si l'US ne concerne que l'affichage d'un jeu

2024-01-12 12:09 UTC, mickaellambert commented on templates/game/_form.html.twig
Je suis pas censé avoir ce fichier si l'US ne concerne que l'affichage d'un jeu

2024-01-12 12:09 UTC, mickaellambert commented on templates/game/edit.html.twig
Je suis pas censé avoir ce fichier si l'US ne concerne que l'affichage d'un jeu

2024-01-12 12:09 UTC, mickaellambert commented on templates/game/index.html.twig
Je suis pas censé avoir ce fichier si l'US ne concerne que l'affichage d'un jeu

2024-01-14 21:05 UTC, Baptiste1828 commented on assets/scripts/carousel.js
Oui, après c'est celui que Nicolas avait fait de son côté que j'ai récupéré et adapté en fonction, avec un carousel vertical en plus

2024-01-22 13:25 UTC, mickaellambert approved these changes

2024-01-22 13:25 UTC, merged